name: ruby-versions
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  run:
    name: ruby
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ["2.4", "2.5", "2.6", "2.7", "head", "jruby", "jruby-head"]
        exclude:
          - os: windows-latest
            version: "jruby"
          - os: windows-latest
            version: "jruby-head"
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
      - name: ruby version
        run: ruby -v
      - run: bundler install
        name: install
      - run: bundler exec rake -t
        name: test
